// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLYL0r68ZkkRwYBelx0rafec-K34oKWWU',
    appId: '1:504672362705:web:85895f4bfb385f95b625f0',
    messagingSenderId: '504672362705',
    projectId: 'bulka-afc6d',
    authDomain: 'bulka-afc6d.firebaseapp.com',
    storageBucket: 'bulka-afc6d.appspot.com',
    measurementId: 'G-1QQ03JLPYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYA-VKv9J5O86sexaPdgcYb6RJh-K5sio',
    appId: '1:504672362705:android:4179bac737eb0e01b625f0',
    messagingSenderId: '504672362705',
    projectId: 'bulka-afc6d',
    storageBucket: 'bulka-afc6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKdWCCnuCifP4xIrgEJB1wvEACnmnOYb8',
    appId: '1:504672362705:ios:833b28d06dae8d31b625f0',
    messagingSenderId: '504672362705',
    projectId: 'bulka-afc6d',
    storageBucket: 'bulka-afc6d.appspot.com',
    iosBundleId: 'abwab.digital.bulka',
  );
}
